# Uncomment the next line to define a global platform for your project
 platform :ios, '12.4'

target 'Safe Wickers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Safe Wickers
  pod 'Cosmos', '~> 21.0'
  
end
